name: Update Omnistrate Plan
description: "Update an Omnistrate plan with a new compose file"

inputs:
  username:
    description: "The username to use for authentication"
    required: true
  password:
    description: "The password to use for authentication"
    required: true
  file:
    description: "The file to update the plan with"
    required: true
  service-name:
    description: "The name of the service to update"
    required: true
  environment:
    description: "The environment to update the plan with"
    required: true
  environment-type:
    description: "The type of environment to update the plan with"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Omnistrate CTL
      uses: omnistrate/setup-omnistrate-ctl@v1
      with:
        email: ${{ inputs.username }}
        password: ${{ inputs.password }}
        version: latest

    - name: Update plan using Omnistrate CTL
      shell: bash
      run: |
        set -e
        
        echo "Omnistrate CTL version:"
        omctl --version
        
        echo "Checking the file content:"
        cat "${{ github.workspace }}/${{ inputs.file }}"
        
        echo "Updating plan with file: ${{ inputs.file }}"
        omctl build -f "${{ github.workspace }}/${{ inputs.file }}" -n "${{ inputs.service-name }}" --environment "${{ inputs.environment }}" --environment-type "${{ inputs.environment-type }}" --release-as-preferred
