x-omnistrate-service-plan:
  name: hello-world-pro
  tenancyType: OMNISTRATE_DEDICATED_TENANCY

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

x-omnistrate-image-registry-attributes:
  ghcr.io:
    auth:
      password: $IMAGE_REGISTRY_PASSWORD
      username: $IMAGE_REGISTRY_USERNAME

services:
  hello-world:
    image: $IMAGE_URI
    ports:
      - target: 3000
    privileged: true