x-omnistrate-service-plan:
  name: hello-world-free
  tenancyType: OMNISTRATE_MULTI_TENANCY

x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics

x-omnistrate-image-registry-attributes:
  ghcr.io:
    auth:
      password: $IMAGE_REGISTRY_PASSWORD
      username: $IMAGE_REGISTRY_USERNAME

services:
  hello-world:
    image: ghcr.io/omnistrate/ci-cd-example:latest # this does not work, because at the moment you push to prod, we need to replace the version during release
    ports:
      - target: 3000
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M