name: Release new version # we should trigger a different workflow instance per plan, can we make the plan a parameter of the environment?

on:
  release:
    types: [ "published" ]
  workflow_dispatch:

env:
  # Image name
  IMAGE_NAME: ${{ github.repository }}

  # The registry to push the image to.
  REGISTRY: ghcr.io # TODO: Change this to docker.io if you are using Docker Hub
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  # Platforms to build the image for
  PLATFORMS: linux/arm64,linux/amd64 # TODO: Add more platforms if needed

  # Omnistrate settings
  OMNISTRATE_USERNAME: ${{ secrets.OMNISTRATE_USERNAME }}
  OMNISTRATE_PASSWORD: ${{ secrets.OMNISTRATE_PASSWORD }}
  OMNISTRATE_SERVICE_NAME: hello-world # TODO: Change this to your service name
  OMNISTRATE_DEV_ENVIRONMENT_NAME: Dev # TODO: Change this to your dev environment name
  OMNISTRATE_PROD_ENVIRONMENT_NAME: Production # TODO: Change this to your prod environment name

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./dockerfile # TODO: Change this to your Dockerfile path
            image-name: env.IMAGE_NAME

    permissions:
      contents: read
      packages: write
      id-token: write

    concurrency:
      group: package-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image-name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
            latest

      - name: Get image URI with SHA tag
        id: get-image-uri
        run: |
          sha_tag=$(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' | grep 'sha')
          echo "IMAGE_URI=$sha_tag" >> $GITHUB_ENV

      - name: Build and push multi-arch
        timeout-minutes: 20
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            # TODO: Add build arguments here if needed
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        plans: # TODO: Change this to your list of plans. Set the file attribute to the path of the spec file.
          - file: compose.free.yaml
          - file: compose.pro.yaml
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace Variables
        run: |
          sed -i 's/$IMAGE_REGISTRY_PASSWORD/${{ env.REGISTRY_PASSWORD }}/g' ${{ matrix.plans.file }}
          sed -i 's/$IMAGE_REGISTRY_USERNAME/${{ env.REGISTRY_USERNAME }}/g' ${{ matrix.plans.file }}
          sed -i 's/$IMAGE_URI/${{ env.IMAGE_URI }}/g' ${{ matrix.plans.file }}

      - name: Update Omnistrate plan in dev environment
        uses: ./.github/actions/update-omnistrate-plan
        with:
          username: ${{ env.OMNISTRATE_USERNAME }}
          password: ${{ env.OMNISTRATE_PASSWORD }}
          file: ${{ matrix.plans.file }}
          service-name: ${{ env.OMNISTRATE_SERVICE_NAME }}
          environment: ${{ env.OMNISTRATE_DEV_ENVIRONMENT_NAME }}
          environment-type: dev

  deploy-to-prod:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        plans: # TODO: Change this to your list of plans. Set the file attribute to the path of the spec file.
          - file: compose.free.yaml
          - file: compose.pro.yaml
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Production Environment if not exist
        uses: ./.github/actions/create-prod-env-if-not-exist
        with:
          username: ${{ env.OMNISTRATE_USERNAME }}
          password: ${{ env.OMNISTRATE_PASSWORD }}
          service-name: ${{ env.OMNISTRATE_SERVICE_NAME }}
          dev-environment-name: ${{ env.OMNISTRATE_DEV_ENVIRONMENT_NAME }}
          prod-environment-name: ${{ env.OMNISTRATE_PROD_ENVIRONMENT_NAME }}

      - name: Replace Variables
        run: |
          sed -i 's/$IMAGE_REGISTRY_PASSWORD/${{ env.REGISTRY_PASSWORD }}/g' ${{ matrix.plans.file }}
          sed -i 's/$IMAGE_REGISTRY_USERNAME/${{ env.REGISTRY_USERNAME }}/g' ${{ matrix.plans.file }}

      - name: Update Omnistrate plan in prod environment
        uses: ./.github/actions/update-omnistrate-plan
        with:
          username: ${{ env.OMNISTRATE_USERNAME }}
          password: ${{ env.OMNISTRATE_PASSWORD }}
          file: ${{ matrix.plans.file }}
          service-name: ${{ env.OMNISTRATE_SERVICE_NAME }}
          environment: ${{ env.OMNISTRATE_PROD_ENVIRONMENT_NAME }}
          environment-type: prod